---
- hosts: allhosts
  gather_facts: true
  become: yes
  remote_user: root 

  tasks:
    - name: install packages
      command: /sbin/apk add unzip curl wget wireguard-tools open-iscsi
      
    - name: Update repositories and install wget and curl packages
      community.general.apk:
        name: wget,curl
        update_cache: true
        
    - name: mount shared root FS 
      command: mount --make-shared /

    - name: Create start file make-shared-root.start
      copy:
        dest: /etc/local.d/make-shared-root.start
        content: |
          mount --make-shared /

    - name: Enable local.d on startup
      command: rc-update add local default

    - name: Add executable on local startup
      command: chmod +x /etc/local.d/make-shared-root.start 

    - name: start local.d 
      command: rc-service local start

- hosts: master
  gather_facts: true
  become: yes
  remote_user: root 

  tasks:
    - name: Copy master scripts to node
      ansible.builtin.copy:
        src: master.sh
        dest: /tmp/master.sh
        mode: '0755'
    
    - name: Run the master script 
      command: sh /tmp/master.sh

    - name: Fetch the config file
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: k3s

- hosts: agent
  gather_facts: true
  become: yes
  remote_user: root 

  tasks:
    - name: Copy agent scripts to node
      ansible.builtin.copy:
        src: agent.sh
        dest: /tmp/agent.sh
        mode: '0755'
    
    - name: Run the agent script 
      command: sh /tmp/agent.sh

